package dev.chatmoderation.gate;

public enum GateEvaluationCategory {
    DIRECT_INSULT,
    INDIRECT_INSULT,
    FAMILY_INSULT,
    DIRECT_SEXUAL_REQUEST,
    SEXUAL_HARASSMENT,
    ADVERTISEMENT,
    NOVEL_ABUSE,
    SEVERE_PROFANITY,
    NORMAL_CHAT,
    BENIGN_SECOND_PERSON,
    REPORT_OR_QUOTE,
    EDUCATIONAL,
    BENIGN_HOMONYM,
    PROPER_NOUN,
    TECHNICAL_TERM,
    NORMAL_CRITICISM,
    REFERENCE_TEXT
}
